### ISSUE TITLE
backoffice: Librarian can search for patrons

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#103]
Tasks:
- [x] Create a patron search page
  - [x] Librarian should be able to search by name, ccid, email.

**Comment by kpsherva** [comment]
HINT: invenio-accounts-rest available
TO decide about LDAP?

**Comment by zzacharo** [comment]
- [ ] Create a patron search page
  - [ ] User should be able to search by name, ccid, email.
- [ ] A task should be created to import ldap users to our system so can be in sync.
  - [ ] Clean up task for checking and removing users that they are not longer in CERN users.
