### ISSUE TITLE
ui: backend errors should be human readable

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#105]
- [x] exception thrown in backend should be returned as error codes by the API - Parent #193
- [x] UI app should have a mapping of error code -> message and display to the user a human readable message - Parent #194

**Comment by topless** [comment]
There is no direct mapping to error and messages. The proper messages are send by the server and we provide in the front end the Error Class so the developer can customise it further on demand.

**Comment by topless** [comment]
resolved by #207
