### ISSUE TITLE
Docker installation error

### ISSUE THREAD

**Issue by tkfischer** [inveniosoftware/invenio-app-ils#1070]
I was asked to check the invenio projects for use in our library. I tried RDM Demo installation and it works well and the demo was so easy to bring up. So was excited to step up and test this system, but the Docker does not want to work...

## Describe the bug
So, I followed the instruction from here https://invenioils.docs.cern.ch/preview/  and it seems to chug along and build the thing. But after the build I go 127.0.0.1 and it goes:
##
503 Service Unavailable
No server is available to handle this request.

## Steps to Reproduce
1. Followed the instructions per above, but after it failed, I removed all Docker images and containers completely (with docker rmi and docker system prune) and built everything from scratch. 
2. The build went fine and from what I can tell, the services are running in Docker similar to RDM, but I get the error on the terminal (error keeps repeating):
##
frontend_1  | 2021/03/22 13:38:24 [error] 27#27: *425 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.10, server: _, request: "HEAD /ping HTTP/1.1", upstream: "uwsgi://172.18.0.8:5000", host: "localhost"
frontend_1  | 172.18.0.10 - - [22/Mar/2021:13:38:24 +0000] "HEAD /ping HTTP/1.1" 502 0 "-" "-" "-"
backend_1   | [pid: 11|app: 0|req: 157/213] 172.18.0.10 () {40 vars in 433 bytes} [Mon Mar 22 13:38:24 2021] HEAD /ping => generated 0 bytes in 17 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 1)

## Expected behavior
RDM install from Docker works great, so my local Docker setup is ok. In any case, I am on a Mac with most of the latest updated software, e.g. Docker version 20.10.5 and also use Docker Desktop

## Screenshots (if applicable)
I was wondering if it was because of no data, and so further tried to run the 
"docker exec  ... setup script"
using the running backend container id, but get the below error 
##
/bin/bash: invenio@d614adb177d3:/opt/invenio_app_ils/src$: No such file or directory

## Context
So, i tried a few more experiments with docker run and docker-compose run, but all of which was of no avail. There was another error with DB table missing, although Postgres build was ok. Is it a real error or bcoz of missing data ?
##
db_1        | Success. You can now start the database server using:
db_1        |     pg_ctl -D /var/lib/postgresql/data -l logfile start

backend_1   |     cursor.execute(statement, parameters)
backend_1   | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "pages_page" does not exist
backend_1   | LINE 2: FROM pages_page
backend_1   |              ^
backend_1   | 
backend_1   | [SQL: SELECT pages_page.created AS pages_page_created, pages_page.updated AS pages_page_updated, pages_page.id AS pages_page_id, pages_page.url AS pages_page_url, pages_page.title AS pages_page_title, pages_page.content AS pages_page_content, pages_page.description AS pages_page_description, pages_page.template_name AS pages_page_template_name 
backend_1   | FROM pages_page]
backend_1   | (Background on this error at: http://sqlalche.me/e/13/f405)

backend_1   | [2021-03-22 13:26:56,708] WARNING in views: Pages were not loaded.
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
backend_1   |     cursor, statement, parameters, context
backend_1   |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
backend_1   |     cursor.execute(statement, parameters)
backend_1   | psycopg2.errors.UndefinedTable: relation "pages_page" does not exist
backend_1   | LINE 2: FROM pages_page

Would be great to get this Docker installation working similar to the RDM cookie cutter demo, which was cool. Happy to answer any questions and/or look into further troubleshooting.

/Tim

**Comment by tkfischer** [comment]
Circling back here. Was able to get it running a while ago by adding the lines to publish the container port to the host like so in docker-compose.full.yml, under service frontend:
   ports:
      - "80:80"
      - "443:443"
 
Can also be done on the command line. 
Another error was due to conflict of ports b/w backend and worker using the same image. To resolve, move the ports from docker-services.yml backend: to docker-compose.full.yml backend:

The sqlalchemy.exc.ProgrammingError was resolved upon downgrading docker desktop from the 3.x version to 2.5.0.1. I am not sure how they are connected, but it is what it is and your mileage may vary.

Maybe helps someone tryin to take a quick look.

**Comment by ntarocco** [comment]
@tkfischer hi! sorry for the late reply, I missed your issue. Were you able to solve it in the end?
For quick help, I would recommend you to join our chat so you can ping me/us and it will be easier to debug when there are specific errors. See how to get access [here](https://inveniosoftware.org/documentation/) (Getting help -> chat)

**Comment by luis575497** [comment]
Cannot create docker container.

**Context**
- git version 2.33.0
- Docker version 20.10.8, build 3967b7d28e
- docker-compose version 1.29.2, build 5becea4c

**Error**
Creating an optimized production build...
Failed to compile.

./src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/schema.js
  Line 130:18:  '_' is not defined  no-undef
  Line 131:11:  '_' is not defined  no-undef

Search for the keywords to learn more about each error.


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @inveniosoftware/react-invenio-app-ils@1.0.0-alpha.51 build: `craco build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @inveniosoftware/react-invenio-app-ils@1.0.0-alpha.51 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-26T23_01_20_244Z-debug.log
The command '/bin/sh -c REACT_APP_INVENIO_UI_URL="https://127.0.0.1"  REACT_APP_INVENIO_REST_ENDPOINTS_BASE_URL="https://127.0.0.1/api"  REACT_APP_ENV_NAME="dev"  npm run build' returned a non-zero code:

**Comment by ntarocco** [comment]
> Cannot create docker container.
> 
> **Context**
> 
>     * git version 2.33.0
> 
>     * Docker version 20.10.8, build 3967b7d28e
> 
>     * docker-compose version 1.29.2, build 5becea4c
> 
> 
> **Error**
> Creating an optimized production build...
> Failed to compile.
> 
> ./src/lib/pages/backoffice/ILL/BorrowingRequest/BorrowingRequestEditor/schema.js
> Line 130:18: '_' is not defined no-undef Line 131:11: '_' is not defined no-undef
> 
> Search for the keywords to learn more about each error.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @inveniosoftware/react-invenio-app-ils@1.0.0-alpha.51 build: `craco build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the @inveniosoftware/react-invenio-app-ils@1.0.0-alpha.51 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /root/.npm/_logs/2021-08-26T23_01_20_244Z-debug.log
> The command '/bin/sh -c REACT_APP_INVENIO_UI_URL="https://127.0.0.1" REACT_APP_INVENIO_REST_ENDPOINTS_BASE_URL="https://127.0.0.1/api" REACT_APP_ENV_NAME="dev" npm run build' returned a non-zero code:

@luis575497 Thank you for reporting this. This was unfortunately created by a wrong import merged to `master` in one recent PR.
The `Docker` files are there to test the app and the `master` branch might be unstable from time to time, as it used as development branch.
If it happens again, you might want to use the latest released `git tag` instead: you will have to change the code is cloned with the Dockerfiles [here](https://github.com/inveniosoftware/invenio-app-ils/blob/master/docker/frontend/Dockerfile#L12).
