### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by homocomputeris** [inveniosoftware/invenio-app-ils#1187]
There are 3 links to docs in the repo:
 - https://invenioils.docs.cern.ch/
 - https://invenio-app-ils.readthedocs.io/
 - https://invenio_app_ils.readthedocs.io/ (broken: HTTP 400)

Which is the most-up-to-date?

**Comment by kpsherva** [comment]
to fix in the documentation:
- [ ] `invenio-cli check-requirements --development` - it is not suitable to be used with invenio-app-ils (points to rdm)

**Comment by kpsherva** [comment]
Hello @homocomputeris,
Thank you for your interest in the software! 
https://invenioils.docs.cern.ch/ is the reference documentation, we will fix the links, thank you for pointing it out!
