### ISSUE TITLE
Change the item status name from LOANABLE 

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#119]
the status name of an item is creating confusion - the state should be descriptive that item is able to circulate. It should be changed both in app-ils and in invenio-circulation

**Comment by kpsherva** [comment]
possible names:

ITEM status to replace LOANABLE:

* USABLE  <- we tend to go with this one
* FUNCTIONAL
* CAN CIRCULATE

* OPERATIONAL
* OPERATIVE
* IN SERVICE
* IN ORDER
* READABLE
* ON CATALOGUE

Circulation naming:

replace `is_item_available` API naming by `has_active_loan` and use the negation of it.
for short naming, describe items as loanable.

**Comment by ntarocco** [comment]
given that previous names are apparently NOGO, other possible names:
* OPERATIONAL
* OPERATIVE
* IN SERVICE
* IN ORDER
* READABLE
* ON CATALOGUE

**Comment by vlad-bm** [comment]
More names:
* OBTAINABLE
* PROCURABLE
