### ISSUE TITLE
Email notifications: updates

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio-app-ils#16]
Setup email notifications for actions done on a loan

**Comment by ntarocco** [comment]
**Tasks to do**
* define configurable email address for librarians (or the list of librarian users) that will receive notifications
* send email notification with user/librarian comments on signals sent
* email notification should probably use [invenio-mail](https://github.com/inveniosoftware/invenio-mail), in any case an async task
* it would be nice to have a simple interface with all sent emails (search? can be a very long list...)
* it would be nice to have an easy way to test

**When to send**
* send notification on loan requests, to requester and librarians:
  * is they any `loanable` item? confirm successful request to the requester, the librarian will handle the request
  * 0 `loanable` items, of 0 attached item to the document, or none with status `loanable`? text should say that the book is requested but it will be evaluated by the librarians
* send notification on loan checkout:
  * send email saying that the loan has started on date `x`, it will end on date `y`.
  * when overriding in CERN overlay, we should add that IF it has been requested office delivery, then it is in transit.
* send notification on loan checkin
* send notification on loan cancelled with comments

Text should be somehow configurable (at least at build/config time, not runtime)

**Comment by kpsherva** [comment]
we have also manual e-mail reminders sending in the requirements so we should provide endpoint in API for that,  @ntarocco WDYT?

**Comment by ntarocco** [comment]
There is a dedicated issues to send reminder: https://github.com/inveniosoftware/invenio-app-ils/issues/17. I will add this!

**Comment by equadon** [comment]
### Notes

- Check if the blueprint for mail should be registered in InvenioMail or in each application
- ~~Check if the celery task in InvenioMail can use `TemplatedMessage` instead of `Message`~~
    - Since `Message` isn't serializable for Celery we can just send `msg.__dict__` as data to the task so using `Message` should be fine

**Comment by ntarocco** [comment]
@equadon it would be nice to add/ensure that there is a log for all the e-mail sent, in case at some point we need to check if an e-mail has been sent or not.

**Comment by equadon** [comment]
@ntarocco yes, that would be great to have. I'll add it.
