### ISSUE TITLE
Email notifications: reminders

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio-app-ils#17]
**GOAL**
Librarian to be able to send email reminders to the patrons who exceeded the loan end date without returning the book.
System to automatically send the reminder if the book is not returned on time. Configurable variable of how frequent the celery task should be triggered.
Celery task should run every day and send reminders for loans which expire today or X days ago, where X is configurable.

**Implementation**
Implement rest endpoint with loanid to send the reminder to the current patron of the exceeded loan.
Implement celerybeat task
Use the celery task for sending the manual ones.

**Comment by kpsherva** [comment]
https://codimd.web.cern.ch/0p-ZhZDnTAycgWGNULBXBQ#UC-Librarian-can-notify-users-for-expired-loans
