### ISSUE TITLE
Record restriction when searching

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#177]
We have implemented record restriction for CRUD operations, but nothing when searching.
We need to add `_access` handling problably on mappings too and override default search class to filter results for restricted records.

Moreover, how do we avoid searching in the `_access` field? It should be stored and available in ES, but not searchable... It is apparently quite complex in ES.

**Comment by kpsherva** [comment]
HINT: check if the most loaned books on the / (home) feature is not broken by permission handling

**Comment by ntarocco** [comment]
Implemented
