### ISSUE TITLE
Support for restricted documents and items

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio-app-ils#18]
Handle *_access* on documents/items

**Comment by ntarocco** [comment]
Unfortunately the development introduced a bug and not you cannot get anymore the details of records. For example: `/api/items/1`:
```
    if not permission_factory(record=record).can():
TypeError: __init__() takes exactly 3 arguments (2 given)
```

`invenio-records-rest` is calling the new class `RecordPermission` passing the `record` param in the constructor.
Also notice that `invenio-records-rest` does not pass the `action` name, so the RecordPermission should be changed to have one method/class per `action`.

It would be nice to add also a REST test to catch this.
