### ISSUE TITLE
Change item status should check for linked loans

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#182]
If an item has `LOANABLE` status and it is changed to something else (for example `MISSING`) then the system should check if there is any active or pending loan on it and in this case:

* BLOCK the change, the active loan should be cancelled first.
**or**
* invalidate any active loan?

**Comment by kpsherva** [comment]
IMO it should block the change because it required validating the data manually, and it eliminates  the possibility of losing a book due to data inconsistencies

**Comment by kpsherva** [comment]
please discuss with the team which solution of the proposed ones is better

**Comment by ntarocco** [comment]
Agree with Karolina:
* block the update
* return an error message explaining exactly why the update failed: which loan PID is blocking, and maybe a link to it, so the librarian can act on this
