### ISSUE TITLE
Tags: record editing and creation

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#203]
OLD ISSUE > Librarian can edit keywords using the record editor.
> The input should allow freetext to add new keywords (create new keyword records), or should prompt autocompletion. (record editor feature)
> 
> What about deletion of keywords? Note that keywords are currently not exposed as REST endpoint.

Create react form for creation/edition purposes of the keyword record type.

take into account that the way of implementing will be used for other record types:
https://github.com/inveniosoftware/invenio-app-ils/issues/464

Choose the technology based on the comments below. @equadon has already done the research, consult with him.

**Goal:**
User is able to add/edit a keyword instance using react form

**Implementation**
React form using invenio-records-rest API for CREATE UPDATE actions. 
It has to be available only for authenticated Librarian role
The feature should be accessible in the backoffice search results and (detail page ?)

**Comment by equadon** [comment]
I evaluated 3 React libraries that generate forms based on the JSON schema and all of them supported:

* Render form for the document schema (with small modifications) with nested keywords quite well
* Possible to add new widget types and modify the look-and-feel
* Validation

Unfortunately neither of them were designed with Semantic UI so there would be some effort to customize the look-and-feel.

https://github.com/mozilla-services/react-jsonschema-form (6095 stars)

```diff
+ Very active
+ Decent documentation
+ Most customizable
+ UI config separate from JSON schema
- Bootstrap
```

https://github.com/networknt/react-schema-form (258 stars)

```diff
* Port of `angular-schema-form` for React.
+ Active
+ UI config separate from JSON schema
- No documentation except README and examples
- material-ui
```

https://github.com/Limenius/liform-react (142 stars)

```diff
+ Uses redux-form
- Mixes UI settings in JSON schema
- Bootstrap
- Last updated 4 months ago
- Not much documentation
```

Screenshots of the generated forms (`react-jsonschema-form`, `react-schema-form`, `liform-react`):

<img src="https://user-images.githubusercontent.com/9783490/55163865-dc8b2300-516a-11e9-9ff1-4b88e8811bf6.png" alt="alt text" height="250">

**Comment by zzacharo** [comment]
@equadon what about autocompletion?

**Comment by egabancho** [comment]
I think our CAP friends are using r[eact-jsonschema-form](https://github.com/cernanalysispreservation/analysispreservation.cern.ch/blob/master/ui/package.json#L49) perhaps it's worth asking their opinion about it

**Comment by ntarocco** [comment]
@equadon nice, thank you for the investigation!
I guess it is quite complex to customize the look and feel and use Semantic UI, right?
I found this, but I am not sure it make any sense: https://github.com/nilportugues/react-jsonschema-form-semanticui

**Comment by equadon** [comment]
@zzacharo Only `networknt/react-schema-form` had an auto-completion built-in but it wasn't as good as `invenio-record-editor` and not really usable in our case. But there are several alternatives for React like https://react-autosuggest.js.org/ and adding a new component in the JSON schema form libraries is trivial.

@egabancho Thanks! Will look into that.

@ntarocco Nice find! The cleanest approach would be to rewrite the widgets using Semantic UI React and the  `nilportugues/react-jsonschema-form-semanticui` repo seems to have done most of the hard work to convert them already but I'm not sure how up-to-date it is.

**Comment by kpsherva** [comment]
decided to create separate forms for edit/create for every record type in react-js. Abandoning the record-editor

**Comment by zzacharo** [comment]
Update: Using [formik](https://jaredpalmer.com/formik/) eventually for the editor forms.
