### ISSUE TITLE
PR 198  fixes

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#210]
there are few fixes to be done after https://github.com/inveniosoftware/invenio-app-ils/pull/198
- [x] reimplement the `setTimeout` function to be run with the loader "loading" state while waiting for timeout - the timeout is set to handle latency of elasticsearch propagation, after discussions `setTimeout` seems to be the easiest solution, not introducing additional complexity to the ui code
- [x] https://github.com/inveniosoftware/invenio-app-ils/pull/198#discussion_r265204258
- [x] https://github.com/inveniosoftware/invenio-app-ils/pull/198#discussion_r265207372 (the list of API urls - normalisation)
- [x] https://github.com/inveniosoftware/invenio-app-ils/pull/198#discussion_r265210550 <- to be discussed
- [x] the error handling has to be implemented for the functionality this PR provides
- [x] https://github.com/inveniosoftware/invenio-app-ils/pull/198#discussion_r265237331
- [x] https://github.com/inveniosoftware/invenio-app-ils/pull/198#discussion_r265228829 (confirmed with others, that it is ok way)

**Comment by equadon** [comment]
I fixed some of those issues in https://github.com/inveniosoftware/invenio-app-ils/pull/207

Changes:
* Implemented error handling
* Renamed `ItemsSearch` class from `ItemsCheckout` to `ItemsSearch`
* Fixed some response type issues (expected array but got object)
