### ISSUE TITLE
Error handling for non-ILS exceptions

### ISSUE THREAD

**Issue by equadon** [inveniosoftware/invenio-app-ils#213]
When raising a non-`RESTException` (e.g. `raise KeyError("test")`) the server returns a `500` without response data.

How do we handle raises of non-`RESTException` exceptions? Should we register an error handler for the base `Exception` class and return a JSON object?

**Comment by FlorianCassayre** [comment]
In **non-debug** mode, the server returns the following (properly serialized) JSON response:
```json
{
  "message": "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.",
  "status": 500
}
```
In debug mode the response is indeed empty (should we change that?).

Closing issue.
