### ISSUE TITLE
Back-office UI: Librarian can see patron information

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio-app-ils#23]
* account info
* past and current loans

depends on #71

**Comment by kpsherva** [comment]
User profile mockup: https://invenio.mybalsamiq.com/projects/cdsbooks/10%20-%20User%20profile

After discussion with the team there is a need to specify what kind of an account info we will provide here, because it's not sure yet we will have users in the db

**Comment by kprzerwa** [comment]
(requires https://github.com/inveniosoftware/invenio-app-ils/issues/71)

**Comment by kpsherva** [comment]
Depends on https://github.com/inveniosoftware/invenio-app-ils/issues/71
