### ISSUE TITLE
UI: Checkout this Item does not work

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#239]
How to reproduce :
/backoffice/items/3 (find an item not ON_LOAN)
Click on 'checkout this item'
Modal has no form. When you try to check out it throws as exception

(requires #227)

**Comment by equadon** [comment]
The UI error is fixed in https://github.com/inveniosoftware/invenio-app-ils/pull/229 but the server still responds with an error depending on the status of the item.

Related to #227.
