### ISSUE TITLE
Errors reported twice to Sentry

### ISSUE THREAD

**Issue by equadon** [inveniosoftware/invenio-app-ils#244]
Sentry logs errors twice (issue from PR #236).

Possibly related to https://github.com/getsentry/raven-python/issues/1081

**Comment by ntarocco** [comment]
@equadon might be because of [this](https://github.com/inveniosoftware/invenio-app-ils/blob/master/invenio_app_ils/ext.py#L28)?

**Comment by FlorianCassayre** [comment]
Closing as the problem seems to have been solved.
