### ISSUE TITLE
backoffice ui: Wrong barcode pasted raises an error

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#253]
If the pasted barcode results in no matches this will raise an error. Is that something we should guard against?

_Originally posted by @equadon in https://github.com/inveniosoftware/invenio-app-ils/pull/240_

**Comment by vlad-bm** [comment]
Do we want any special behaviour (e.g. validation if it's a number conforming to a barcode type)? Or just use the default behaviour when the barcode isn't found?
