### ISSUE TITLE
Parameters passing convention

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#273]
Maybe we should consider object literal as parameters, to provide an example when I see `requestNewLoanForBook('123', {..})` I have no clue what `123` is, I could guess but I am not very good at guessing. We would have something like:

```
requestNewLoanForBook({
    document_pid: '123',
    loan: {...}
})
```

_Originally posted by @topless in https://github.com/inveniosoftware/invenio-app-ils/diffs_

**Comment by ntarocco** [comment]
If you prefer why not, but I would not enforce it as general rule. If I have one param only, I would go for:
`requestNewLoanForBookPID('123')`

**Comment by kpsherva** [comment]
closing as stale
