### ISSUE TITLE
Remove hardcoded states

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#277]
Instead of explicitly comparing strings it might be preferable to have a constant somewhere with all these values.

_Originally posted by @topless in https://github.com/inveniosoftware/invenio-app-ils/pull/274_

**Comment by ntarocco** [comment]
IMHO, we don't need this, it is not runtime configurable but completely hardcoded. The JSON Schema has these strings hardcoded in the JSON file.
