### ISSUE TITLE
[Review] Sprint 10

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#290]
## Review

* Issues: 
  * https://waffle.io/CERNDocumentServer/cds-books?milestone=Sprint%2010
* Timeline: https://cernbox.cern.ch/index.php/s/sWuZHrXKHkC7Hfc

### Migrator kit
- Reviewed data chunks to find not addressed in rules for fields - lot of fields found
- fixed rules for collections and document_types

### Q&A

**Comment by ntarocco** [comment]
https://github.com/CERNDocumentServer/cds-books/issues/47
