### ISSUE TITLE
Back-office UI: Mockups

### ISSUE THREAD

**Issue by ludmilamarian** [inveniosoftware/invenio-app-ils#30]
Starting from the requirements and the existing pages for circulation, create the initial mock-ups for the back-office UI using balsamiq. Some of the mockups have been done in the past (loan page, item page) so the rest can follow a similar approach.

**Comment by costaflavio** [comment]
Discussed the first muckup (Request for a New Book) and since it could be shared with users' use cases, agreed to prepare a preliminary list with all the possible forms/screens needed by the Back-office UI combining the requirements/use cases and the existing pages.

**Comment by costaflavio** [comment]
On 17.10.18 discussed the list of the possible forms/screens

OUTDATED [list of possible pages for Back Office.xlsx](https://github.com/inveniosoftware/invenio-app-ils/files/2491424/list.of.possible.pages.for.Back.Office.xlsx)

UP TO DATE FILE [(link)](https://cernbox.cern.ch/remote.php/webdav/__myprojects/digital-repositories/Services_Projects/CDS/Books/list%20of%20possible%20pages%20for%20Back%20Office.xlsx?x-access-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjoiZmNvc3RhIiwiZ3JvdXBzIjpbXSwiZGlzcGxheV9uYW1lIjoiRmxhdmlvIENvc3RhIChmY29zdGEpIn0.IzE6VYA7P8k9--YZnj3tWjc32OQna-1LYJ5_1nKZtQY)

Agreed that it is needed that the a initial workflow is proposed on the base of the attachment
[Workflow initial mockups 20181017.pdf](https://github.com/inveniosoftware/invenio-app-ils/files/2491285/Workflow.initial.mockups.20181017.pdf)

**Comment by costaflavio** [comment]
Two mockups options for the list of requests available to compare/discuss  (to be refined); other two on going

**Comment by costaflavio** [comment]
All the NUMBERED mockups in https://invenio.mybalsamiq.com/projects/cdsbooks/grid are up to date with the "state of the art" of requirements, mainly from:

- U.C. (final)
- BibCirculation
- lists&stats doc
- discussions (Ludmila, Chris...)

A tab was added in the "Possible pages" [file](https://cernbox.cern.ch/remote.php/webdav/__myprojects/digital-repositories/Services_Projects/CDS/Books/list%20of%20possible%20pages%20for%20Back%20Office.xlsx?x-access-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjoiZmNvc3RhIiwiZ3JvdXBzIjpbXSwiZGlzcGxheV9uYW1lIjoiRmxhdmlvIENvc3RhIChmY29zdGEpIn0.IzE6VYA7P8k9--YZnj3tWjc32OQna-1LYJ5_1nKZtQY) with the mapping between the pages and the lists&stats doc

Missing/to be be improved:
- statuses for items (2 - Loan page)

**Comment by costaflavio** [comment]
A reminder to check:
- collections: the collection is apparently moved from Item to Book during migration. To be checked if the lists/stats have to be done aggregating collections. 

NO: collections are not migrated

**Comment by costaflavio** [comment]
The creation of a loan (typically from barcode scanning) moved to 3 - Item page from 2 - Loan page as it was too complex to combine the creation (no loanID) with the display/modify.
