### ISSUE TITLE
Remove PIDSTORE_RECID_FIELD config

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#307]
When `PUT` or `PATCH` records, Invenio uses loaders to validate the request payload. Currently, [loaders](https://github.com/inveniosoftware/invenio-app-ils/blob/master/invenio_app_ils/records/loaders/schemas/json/document.py#L14) are inheriting from `RecordMetadataSchemaJSONV1`. This class, defined in `invenio-records-rest`, needs some refactoring because it hardcodes a global config [PIDSTORE_RECID_FIELD](https://github.com/inveniosoftware/invenio-app-ils/blob/master/invenio_app_ils/config.py#L681).

What it does is:
* remove any extra field that is sent in the payload and is not defined in the schema class
* automatically read the `pid` param from the url, for example when doing `PUT` `/api/documents/1234`
* inject a new field in the schema, defined by the config `PIDSTORE_RECID_FIELD`, with value `1234`

This means that if `PIDSTORE_RECID_FIELD` is defined as `item_pid`, it will add the document schema `item_pid` and not `document_pid`!!!

To do:
* refactor `invenio-records-rest` to remove this field or to have as default value to avoid breaking APIs, in case some Invenio solutions call the PID field always with the same field name for all records.
* allow this field to be overridable. Instead of reading this PID field name by config, first check if it is configured as class attribute, or read it from a getter/abstract method

**Comment by zzacharo** [comment]
Addressed https://github.com/inveniosoftware/invenio-records-rest/pull/252
