### ISSUE TITLE
As a librarian I should be able to attach a Series from a Document

### ISSUE THREAD

**Issue by equadon** [inveniosoftware/invenio-app-ils#311]
Modifications of relations can be done only from the Document details page.

- [x] move the `Manage` tab into each tab
- [x] simplify the `Manage` dialog box and remove the `Type` field and the tabs at the bottom, given that now when opening the dialog the user is already inside one tab (for example language).
- [x] add new 2 tabs for relation types (Serial | Multipart monograph). Each row of the table is the parent (series). The last column is the relation label (in this case f.e. vol. 1)

**Comment by kprzerwa** [comment]
to discuss also if we handle it in the backoffice UI or record editor

**Comment by kprzerwa** [comment]
TODO:
Document details page: Attach to series functionality.
Series detail page: a table with all attached documents, delete button for each one of them, add button to attach documents one by one (no multiple attaching for now)
