### ISSUE TITLE
Invalid propTypes for AggregatorValues

### ISSUE THREAD

**Issue by topless** [inveniosoftware/invenio-app-ils#316]
For `Documents`, `Items` and `Loans` searches the propTypes are incorrect

```
Invalid prop `values` of type `object` supplied to `AggregatorValues`, expected `array`
```

The AggregatorValues propTypes are defined in https://github.com/inveniosoftware/react-searchkit

**Comment by kpsherva** [comment]
checked, the warning is not there anymore. Closing
