### ISSUE TITLE
Replace withRouter with import history

### ISSUE THREAD

**Issue by topless** [inveniosoftware/invenio-app-ils#317]
There are several components that we wrap them `withRouter` in order to have access to the `history`.

We can just import `src/invenio_app_ils/history` and then `history.push('...');`

**Comment by zzacharo** [comment]
Possible thought to move `history.js` in the `router` module and use the added `goTo` function for navigating.

**Comment by zzacharo** [comment]
Done in https://github.com/inveniosoftware/invenio-app-ils/pull/376
