### ISSUE TITLE
Refactor Container components

### ISSUE THREAD

**Issue by topless** [inveniosoftware/invenio-app-ils#319]
- [x] move all API calls to container
- [x] deprecate the dedicated *Container.js file and move container in `index.js`

**Comment by ntarocco** [comment]
After discussions:
- keep the component `withDataContainer`
- slowly refactor other components
- [PR](https://github.com/inveniosoftware/invenio-app-ils/pull/377) closed in the meanwhile because it is getting very outdated.

**Comment by topless** [comment]
Its gonna take more time to rebase it than replace a few containers. A couple of things that can be used.

- The HOC container [implementation](https://github.com/topless/invenio-app-ils/blob/713b25cf34477976e5dfcfbba3982c6a932ba675/invenio_app_ils/ui/src/invenio_app_ils/common/components/DataContainer/DataContainer.js) 
- Its [usage](https://github.com/topless/invenio-app-ils/blob/713b25cf34477976e5dfcfbba3982c6a932ba675/invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentDetails/index.js) without ContainerComponent

**Comment by kpsherva** [comment]
the UI have evolved now, IMO the issue with the containers was solved
