### ISSUE TITLE
Restructure document and item properties

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#324]
It has been agreed that all the fields internal for the system (not the part of record description) should be encapsulated in the `_computed` field (f.e `circulation` field in the `Document`) 
Comment: I think the field should be name `_system`

**UPDATE**
After a meeting with the team the issue has been discussed and decided to be addressed in a different fashion.

- [x] move `eitems` one level up from `_computed` and remove `_computed`
- [x] ~create `items` for `document` in the same fashion as `eitems`~
- [x] move properties of `circulation` that are relevant to `items` to the newly created `items`
- [x] align `circulation` and `circulation_status` for `document` and `item` respectively

**Comment by kpsherva** [comment]
decided to be `_computed`

**Comment by ntarocco** [comment]
`has` fields should be boolean. Right now, they count the quantity, for example: `has_eitems: 2`. We should have consistent naming.

**Comment by topless** [comment]
After a meeting with the team the issue has been discussed and decided to be addressed in a different fashion.

- [x] move `eitems` one level up from `_computed` and remove `_computed`
- [ ] create `items` for `document` in the same fashion as `eitems`
- [ ] move properties of `circulation` that are relevant to `items` to the newly created `items`
- [ ] align `circulation` and `circulation_status` for `document` and `item` respectively
