### ISSUE TITLE
Sort documents by volume number

### ISSUE THREAD

**Issue by equadon** [inveniosoftware/invenio-app-ils#354]
Currently sorting documents by volume number for a specific series does not work (e.g. in the series details page).

The issue seems to be that since we don't use the `nested` datatype in ES we can't sort by a nested value combined with another (e.g. series PID). A few solutions to this:

1. Use `nested` datatype for `document.series`
- Would allow us to properly filter and sort documents by multiple series fields
- Adds complexity since we cannot use URI search in e.g. in the search bar on documents search page
2. Use `nested` datatype for `document.series_objs`
3. When resolving `document.series` create "dynamic" fields called e.g. `<series_pid>_volume` on document level which we could use to sort by volume number for a specific series PID
4. Sort hits by volume number in JavaScript

**Comment by kpsherva** [comment]
closing as the structure of the series changed
