### ISSUE TITLE
related_record management

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#359]
We need to implement a way of linking records (manual and automatic in future harvests). 
There is 3 types of linking:
- [x] related _record field
- [x] different editions
- [x] series
Multipart monograph can have a relation.

**Comment by equadon** [comment]
Examples of records:
https://cds.cern.ch/record/2636628?ln=en (several languages + editions)
https://cds.cern.ch/record/2640912?ln=en (several languages + editions with multi-volumes)
