### ISSUE TITLE
Add type identifier to indexed ES documents

### ISSUE THREAD

**Issue by equadon** [inveniosoftware/invenio-app-ils#366]
Add an identifier to indexed ES docs so we can identify which index it belongs to. Since patrons doesn't have `$schema` we cannot use it to identify which type of document it is.

_Originally posted by @kprzerwa in https://github.com/inveniosoftware/invenio-app-ils/pull/339_

Possible solutions:
- Add "fake" schema to patrons
- Store index name in returned hits (can ES do this automatically?)

**Comment by kpsherva** [comment]
to discuss if it's necessary or maybe it is already provided

**Comment by kpsherva** [comment]
closing as handled in different way
