### ISSUE TITLE
Related records: backoffice UI

### ISSUE THREAD

**Issue by equadon** [inveniosoftware/invenio-app-ils#373]
Implement backoffice UI for selecting related records. We'll need a way to select a related record and its relation to the record it's added to.

- [x] implement type of relation to select with the drop down (edition/translation)
- [x] implement radio button to choose the endpoint of search (document / series)
- [x] searchbox (reuse existing component)

! to be implemented both in the document details page and series detail page
ensure proper error handling

TO DO what is parent relation type and other?

**Comment by kpsherva** [comment]
to discuss: if we do it in the backoffice UI or it will be handled by record editor

**Comment by ntarocco** [comment]
Cannot be handled by record editor, since we are going for PID relations and not record metadata.
Actually, this field should be hidden from the record editor.
