### ISSUE TITLE
Results table requires `ID` property of the displayed items.

### ISSUE THREAD

**Issue by topless** [inveniosoftware/invenio-app-ils#407]
If we remove `ID` from the list of the properties we want to display, we get 
`Warning: Each child in an array or iterator should have a unique "key" prop.`
so it is also used as key for the iterations.

**Comment by kpsherva** [comment]
you have to provide some unique id for every list item, table cell etc. The thing is that we should be able to turn off the display of `ID`

**Comment by topless** [comment]
Closed in favor of #337

**Comment by topless** [comment]
Closed in favor of #337
