### ISSUE TITLE
Invenio-Accounts-Rest endpoint tests

### ISSUE THREAD

**Issue by topless** [inveniosoftware/invenio-app-ils#408]
Create tests similar to  `test_item_permissions_endpoint.py` for all http methods 

- [ ] `GET`
- [ ] `POST`
- [ ] `PUT`
- [ ] `PATCH`
- [ ] `DELETE`

for the endpoints of `invenio-accounts-rest`, `users/` and `users/{id}`.

**Comment by ntarocco** [comment]
@zzacharo do we remove the module? We might close this task then.....

**Comment by kpsherva** [comment]
this module is removed from app, closing
