### ISSUE TITLE
Paginate results on patron profile page

### ISSUE THREAD

**Issue by equadon** [inveniosoftware/invenio-app-ils#418]
Paginate loan results on the profile page on frontsite, instead of having an infinite list.
Also refactor the UI components and remove any direct backend call: backend call should be in redux actions only.

**Comment by ntarocco** [comment]
- _Paginate loan results on the profile page on frontsite, instead of having an infinite list_: addressed by #440.
- _Also refactor the UI components and remove any direct backend call: backend call should be in redux actions only_: addressed by #439
