### ISSUE TITLE
Statistics dashboard

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#419]
:question: verify the features where it is expected, separate dashboard or specific search pages :question: 

- [x] List of the most loaned books in a period of time - **stats dashboard**
- [x] Number of loans in a period of time 
- [ ] Number of users active within a specific module (circulation/ILL/ACQ) - **#TODO**
- [ ] ~~Number of users active within a specific module (circulation/ILL/ACQ) by department - **#TODO**~~

**Comment by ntarocco** [comment]
@kprzerwa can we review if this is still valid?

**Comment by ntarocco** [comment]
duplication of https://github.com/inveniosoftware/invenio-app-ils/issues/169 ?

**Comment by kpsherva** [comment]
closing as it has only the duplicate task left
