### ISSUE TITLE
Request a loan from document details page

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#430]
To reproduce
1. Create a loan request from document 
2. select user and create a request
3. Request is created with invalidDateTime (startDate and expirationDate)
4. Loan details page shows yellow warning box with undefined item message
 > The Item undefined assigned to this loan has been deleted!

**Comment by vlad-bm** [comment]
I think we need to discuss the following:
* startDate semantics e.g. start date for the request or for the upcoming loan?
* same for expirationDate
* will any of them be user-definable or will they be automatic?
