### ISSUE TITLE
backoffice: Patrons current loans show pending loan requests

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-ils#431]
### Steps to reproduce the bug:
1) Go to a document and create a loan request for a user
2) Then go to patrons search, find the user and navigate to it's profile page
3) In the box "Patron's current loans" you can see the pending loan request appearing there.
4) If you refresh the state is as expected

### Hints:

Before you refresh if you open the network tab the query filtering the state is including the state "PENDING" and actually 2 times!

Update:

The bug is happening because of the way we import the querybuilder instance. In ES6 when you import an object from a file every subsequent import call will end up giving you the same instance. [Here](https://github.com/inveniosoftware/invenio-app-ils/blob/master/invenio_app_ils/ui/src/invenio_app_ils/common/api/loans/loan.js#L225) the query property is ending up giving the same queryBuilder instance every time. Then calling the `withState` helper method mutates the state query. The querybuilder class should not be part probably of the exported object and force instantiation in the places it's used!

**Comment by topless** [comment]
I have tried a several thing approaches to figure out what is going one.

- Explicitly instantiating the QueryBuilder class 
https://github.com/topless/invenio-app-ils/tree/431-explicit-builder
- Reseting the QueryBuilder every time we build a query
https://github.com/topless/invenio-app-ils/tree/431-reset-query

On top of that if you navigate to patron details then navigate somewhere else i.e. documents and back to patron details, all the requests of the page are executed **twice**
