### ISSUE TITLE
Clean record editor

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#465]
remove record editor references from the code and dependencies, also any config variables etc
remove the repository from inveniosoftware organisation

**Comment by topless** [comment]
![RIP](https://user-images.githubusercontent.com/230805/63703582-91646180-c829-11e9-98b2-c4b8a0e518da.jpg)

**Comment by zzacharo** [comment]
Every reference to the editor has been cleaned.
