### ISSUE TITLE
Fix loans search permission

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#47]
[This commit](https://github.com/inveniosoftware/invenio-app-ils/commit/5c908858a67f72f9377f4eeb81f319989aea60b5) has been added to unblock a PR merge, but it should be reverted and fixed.

The issue is that every time an Item is indexed, it will resolve the `$ref` current `circulation status` and perform a search to find the corresponding loan. The search is done using `IlsLoansSearch`  which is restricting the `patron_pid` **and** if you are not in a request context (like `cli`) you have `g.identity` that is `None`.

A solution has to be implemented to search with permissions but index correctly Items.

(related #25)

**Comment by kprzerwa** [comment]
related to #25

**Comment by kpsherva** [comment]
related to #25
