### ISSUE TITLE
Email reminders - backoffice

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#473]
**GOAL**
Librarian to be able to send email reminders to the patrons who exceeded the loan end date without returning the book.

**Implementation**
Manual trigger should be available in the 'Actions' column of the 
- results table of overdue Loans 
- the loans detail page
- the search page for overdue loans

(reusable component). After clicking the button the UI should display "Are you sure" modal.

**Comment by topless** [comment]
For the first case of the Overdue loans list, we have calculated on the backend and we know that they are overdue. 

When we are on the LoansDetails page though the loan does not have the information if it is expired or not, thus we don't know if we should render the send email button. I can think of two ways to address the issue.
- a celery task that runs after midnight and updates a loan property `is_expired` (that property is new to for the loan schema)
- to make the comparison of loan end_date and now, in the ui on the fly
- create loan search and record serializer and decorate loan with `is_overdue` property

We went for the 3rd solution.
