### ISSUE TITLE
check if free item automatically assigned to loan request

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#505]
after merging: https://github.com/inveniosoftware/invenio-circulation/pull/119/files#diff-e552fa87ac46ed2b39a60d80733cf179R179

**Comment by ntarocco** [comment]
This is done, now in ILS by default there is no automatic assignment.
https://github.com/inveniosoftware/invenio-app-ils/blob/master/invenio_app_ils/config.py#L711
I think we can add to the milestone and close :)
