### ISSUE TITLE
[TASK] Loan extension

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#520]
**Backend**
* implement checks and permissions for loan extension feature (taking into account patron and librarian)
* add tests

**Frontend**
* add the `Request extension` button to the patron profile page
* enable/disable based on conditions
* show human readable error messages

Requirement: #261

**Comment by topless** [comment]
@ntarocco, @kprzerwa according to #261 and the relevant [codimd](https://codimd.web.cern.ch/0p-ZhZDnTAycgWGNULBXBQ#UC-User-can-extend-a-loan)

> The extension policy should be configurable: i.e. automatically approved if there is no waiting list, otherwise in the **pending list** to be treated manually by librarian

As I understand it, it implies that there will be an automatic extension, or the loan extend request will go to a list that the librarian will handle manually. This expands the scope of this issue dramatically, do we need something like that? WDYT?

**Comment by kpsherva** [comment]
We discussed with Nico about it, and for now we should leave it like it is, with no extending the ticket. So for now if the book is overbooked, we block the extension possibility and they can contact the librarian to decide the extension for them (the librarian can do it any time anyway)
Let's not extend the scope here

**Comment by ntarocco** [comment]
Issue text updated
