### ISSUE TITLE
formatters: pick data properties instead column titles 

### ISSUE THREAD

**Issue by topless** [inveniosoftware/invenio-app-ils#551]
A suggestion from @zzacharo from pr #549.

Currently when we are formatting data for tables, we filter object's properties based on the table column header.
```JS
data.map(row => pick(formatter.loan.toTable(row), ['ID']))
```

Proposed change, a more straight forward approach to filter on the object's properties and hide the table columns names inside the formatters.
```JS
data.map(row => pick(formatter.loan.toTable(row), ['pid']))
```

**Comment by zzacharo** [comment]
For example here [DocumentItems.js](https://github.com/inveniosoftware/invenio-app-ils/blob/master/invenio_app_ils/ui/src/invenio_app_ils/pages/backoffice/DocumentDetails/components/DocumentItems/DocumentItems.js#L35) should be transformed to something like:

```JS
prepareData(data) {
    return data.hits.map(row => {
      const row = pick(row, [
        'id',
        'pid',
        'created',
        'updated',
        'metadata.title',
        'metadata.authors',
        'metadata.circulation.has_items_for_loan',
        'metadata.circulation.overdue_loans',
        'metadata.circulation.pending_loans',
        'metadata.circulation.past_loans_count',
      ]);
      return formatter.item.toTable(row);
    });
  }
```
