### ISSUE TITLE
Document - Create/Edit form

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#575]
Implement create and edit forms in the UI, based on the latest schema.
The `publication_info/journal_record` field is not finalised
Keep on mind that there might be new fields added for the journals
when someone updates the document fill the `updated_by` field 

make sure the user has proper access rights for the operations. Both backend/frontend. The task is mainly frontend, most of the functionality on the backend should be handled by invenio-records-rest

Simple fields:
- [x] abstract
- [x] alternative_abstracts
- [x] curated
- [x] document_type
- [x] edition
- [ ] extra_data
  - What's in this field?
- [x] note
- [x] number_of_pages
- [x] other_authors
- [x] source
- [x] table_of_content
- [x] title

Complex fields:
- [x] alternative_identifiers (simple)
- [x] alternative_titles
- [x] authors
  - `type` should be a dropdown
- [x] conference_info
  - ~Is series a `series_pid` or just a title?~ **Just a title.**
- [x] copyrights
  - ~DatePickerField doesn't handle correctly the select of the year but it's fine when you type. The event emitted from the underlying library is not correct when selecting a field. Probably needs to be checked if we should use just a string field for now.~ **Fixed**
- [x] identifier (simple)
- [x] imprints
- [x] internal_notes
- [x] keywords (simple)
   - Now it's an object with 2 keys. Shouldn't be an array?
- [x] languages
- [x] licenses
- [x] publication_info
- [x] subjects
- [ ] tags (Requires more discussion on if we keep them as records or go change it to vocabulary)
- [x] urls (reuse from `EItemForm`)

- make sure of:
  - [x] when creating a new document (not when editing), the submit buttons should be probably 3: Create, Create a new item from this document, Create a new eitem from this document (in a nice way!)
  - [x] add the same buttons in the document details page
  - [ ] it would be nice to do exactly the same thing from the Series creation form/details page

**Comment by equadon** [comment]
Authors field structure:
```js
authors: [
  {
    affiliations: [
      {
        identifiers: [
          {
            scheme: 'abc',
            value: 'test',
          }
        ],
        name: 'test name',
      }
    ],
    alternative_names: ['A', 'B'],
    full_name: 'Test',
    identifiers: [
      {
        scheme: 'abc',
        value: 'test',
      }
    ],
    roles: ['asdf'],
    type: 'test',
  }
]
```

**Comment by ntarocco** [comment]
```json
{
    "docid": {
        "document_type": [
           {
             "name": "BOOK",
             "label": "Book",
           }
            ...
         ],
        "alternative_identifiers_schemes": [
            {
                "name": "ARXIV",
                "label": "arXiv",
            },
            {
                "name": "ASIN",
                "label": "Amazon Standard Id. Number (ASIN)",
            },
            {
                "name": "ISBN",
                "label": "International Standard Book Number (ISBN)",
                "default": true
            },
            {
                "name": "HDL",
                "label": "Handle.Net (HDL)",
            },
            {
                "name": "SAFARI",
                "label": "Safari Books Online (SAFARI)",
            },
        ],
        "identifiers_schemes": [
            {
                "name": "DOI",
                "label": "Digital object identifier (DOI)",
                "default": true
            },
            {
                "name": "URN",
                "label": "Uniform Resource Name (URN)",
            },
        ],
        "affiliations_types": [
            {
                "name": "Person",
                "label": "Person",
                "default": true
            },
            {
                "name": "Organization",
                "label": "Organization",
            },
        ],
        "authors_identifiers_schemes": [
            {
                "name": "ORCID",
                "label": "ORCID",
                "default": true
            },
            {
                "name": "ISNI",
                "label": "International Standard Name Identifier (ISNI)",
            },
            {
                "name": "ROR",
                "label": "Research Organization Registry (ROR)",
            },
            {
                "name": "GRID",
                "label": "Global Research Identifier Database (GRID)",
            }
        ],
        "conference_info_identifiers_schemes": [
            {
                "name": "ROR",
                "label": "Research Organization Registry (ROR)",
                "default": true
            },
        ],
    }
}
```
