### ISSUE TITLE
Document form: Extra data field

### ISSUE THREAD

**Issue by equadon** [inveniosoftware/invenio-app-ils#586]
Figure out how we render the `extra_field` in the document form.

One solution could be to provide a form component to `App` to allow customization for how the `extra_data` field is rendered.

**Comment by kpsherva** [comment]
as a reference solution: https://github.com/inveniosoftware/invenio-rdm-records/pull/75

**Comment by topless** [comment]
Closed in favour of https://github.com/inveniosoftware/invenio-app-ils-ui/issues/8
