### ISSUE TITLE
DocumentlCirculation.js overbook indication is wrong

### ISSUE THREAD

**Issue by topless** [inveniosoftware/invenio-app-ils#626]
@kprzerwa what do you think about red checkmarks? is it overbooked or not ? 😕 

![Screenshot 2019-11-26 at 17 43 40](https://user-images.githubusercontent.com/230805/69654018-6251cc00-1074-11ea-88bd-d6d92c149586.png)

**Comment by kpsherva** [comment]
will be solved with my next PR, I close it for now
