### ISSUE TITLE
Acquisition: backoffice UI 

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#630]
Implement the frontend for the acquisition module
Discuss it first, to align on the style 

To discuss:
* Should we allow deleting vendors and orders? 
    * I would say yes... 
    * vendors: only if no orders
    * orders: only if status not completed, basically only if no "foreign-keys" updated (no items referencing the order)
* Should we have an edit button on the search list entries?
  * is this a general question for all search pages? I would say no... let's keep the button in the details page?

**Comment by ntarocco** [comment]
Can you please:
* get rid of the acquisition status `PARTIALLY_RECEIVED`? We are not going to use it any more...
* make sure that `notes` is an array of strings (multiple notes). This is what they requested, even if I am not sure it has a lot of value...
