### ISSUE TITLE
Document request and acquisition integration

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#634]
**Scenario**

A patron creates a document request.

1. The document **does** exist in the library and there are copies:
  * librarian finds the document in the system
  * librarian clicks on the button `Attach document` and attaches it
  * librarian clicks on the button `Cancel request because already in the catalogue`
  * librarian creates a loan for the patron
2. The document **does** exist in the library and there no copies:
  * librarian decides to create acquisition, clicks on the button `Create purchase order`
  * librarian creates the acquisition order by filling the form and clicks on `Create`
  * the document request changes to state `FULFILLED` with the `acquisition_pid` filled in
3. The document **does not** exist in the library:
  * librarian click on the button `Create a document from this request` and attaches it
  * go to point `2`.

**Use cases**

The document request details page in the backoffice should have a few actions/buttons:
* `Cancel request`: remove the cancel reason for DocumentRequest. The cancel should be of 3 types (3 buttons/a button with 3 options?) -  https://github.com/inveniosoftware/invenio-app-ils/issues/667
  * `User cancelled`: the user cancelled for any reason. It can be triggered by the user in the Profile page, or by the librarian because the user asked her/him to do it.
  * `Librarian cancelled because document already in the catalog`: the librarian cancelled because the document is in the catalog but the user did not find it. The librarian will probably then create a loan out of it.
  * `Librarian cancelled because document not found`: the librarian cancelled because the document has not been found in any of the providers/external libraries.
  * An e-mail should be sent to the user in all cases
* `Create a document from this request`: it opens the new document request already pre-filled
  * enabled only when 
    * state `PENDING`
    * a document **is not attached** to the request
  * when disabled, it should say that it is disabled because document already attached or request
  * it would be nice, after the creation of the document, that the DocumentRequest has the new document attached. https://github.com/inveniosoftware/invenio-app-ils/issues/668
* `Attach document`: https://github.com/inveniosoftware/invenio-app-ils/issues/669
  * enabled only when 
    * state `PENDING`
    * a document **is not attached** to the request
  * when disabled, it should say that it is disabled because document already attached or request already fulfilled.
* `Change attached document`: https://github.com/inveniosoftware/invenio-app-ils/issues/669
  * enabled only when 
    * state `PENDING`
    * a document **is attached** to the request
  * when disabled, it should say that it is disabled because document not yet attached or request already fulfilled.
* `Create purchase order`: https://github.com/inveniosoftware/invenio-app-ils/issues/670
  * enabled only when:
    * state `PENDING`
    * a document **is attached** to the request
  * when disabled, it should say that it is disabled because not document attached yet or request already fulfilled.
* `Create ILL`: disabled at the moment, not yet implemented. See: https://github.com/inveniosoftware/invenio-app-ils/issues/637

**Comment by kpsherva** [comment]
the last step defined in tasks for ILL, closing
