### ISSUE TITLE
forms: styling (one hell of an issue)

### ISSUE THREAD

**Issue by topless** [inveniosoftware/invenio-app-ils#666]
- When we are using a `GroupField` and we put together a dropdown (i.e. VocabularyField) and a simple StringField they are not aligned correctly
- Dropdown options are overlapping for example the DatePicker with inputs or the field that you select the currency. [z-index](https://github.com/inveniosoftware/invenio-app-ils/blob/1be9e0fcab393b027ee108e2db12493906443107/ui/src/semantic-ui/site/modules/dropdown.overrides#L25) that causes the problem, if we remove this the forms work as expected.

( connected with #683 )

**Comment by kpsherva** [comment]
I will put everything into one issue. and close this one
