### ISSUE TITLE
Export: error when changing page

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#675]
Try to export search results to CSV not from the first page but from the second.

`q=&sort=mostrecent&page=2&size=10000&format=csv`
```
SearchPaginationRESTError: 400 Bad Request: Maximum number of 10000 results have been reached.
```

This is because Invenio-Records-REST counts the 10K max from page 2 (to be investigated).
Maybe the export should not take into account the `page` when `size=10000`?

EDIT: The problem is coming from ElasticSearch itself, the Page size is set to 10000 for performance reasons. 
The easy fix for now is to limit the export to 10k results, always on "page" 1.

**Comment by ghost** [comment]
Hi Nicola, I bumped into the same issue.
In my case it does not matter how many records are in each page, ones you reach 10.000 it gives the error you mentioned.
Have you found any way do deal with this problem?
Thanks,
Matias

**Comment by ntarocco** [comment]
We did not address the issue, but we will for sure before releasing ILS as a stable product, because this is a must have feature.
Unfortunately we do not have yet an estimation. Are you blocked by this? Can it wait?

**Comment by ghost** [comment]
It can wait for now but I will definitely need it in the coming months.
Thanks again

**Comment by ntarocco** [comment]
Perfect, than we will prioritize it, ping @kprzerwa 
Out of curiosity, and maybe we can switch this conversation to a chat, are you using this ILS project in your environment?
It would be nice to understand if it fulfils your requirements somehow... It is still under development, and the doc is not yet available.

**Comment by ghost** [comment]
No, actually I am using RDM, but the issue is the same.
Looking forward to have some updates

**Comment by FlorianCassayre** [comment]
Fixed by inveniosoftware/react-invenio-app-ils#180
