### ISSUE TITLE
SPA Authentication - login stuck after backend error

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-ils#709]
Actual
---
After a backend error, e.g. validation error, the frontsite React app logout the user. The user cannot login any more and he is stuck.
The frontend is logged out, but the backend still logged in. When trying a new login to /api/login, the backend return 302 redirect since it is already logged in. The frontend cannot handle this.
The webpage is blank/white.

Steps to reproduce
---
1. have an instance running
2. login as you should
3. go to backoffice
4. trigger a Validation error or any error: e.g. form submission error when creating a record
5. you should see on the top right the red error notification

Temporary workaround
---
Clean the auth cookie created on localhost:5000, so the backend is also logged out.

More
---
* the react app, on logout, should redirect to homepage, it is not happening.
* Probably invenio-account `/api/login` should not redirect 302, but return a response saying "already logged in"

**Comment by kprzerwa** [comment]
I couldn't reproduce this bug

**Comment by kpsherva** [comment]
@ntarocco we have fixed it, can you also test it to confirm?

**Comment by ntarocco** [comment]
It looks fixed to me now!
