### ISSUE TITLE
Backoffice: Display user profile info in patron details

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#71]

**Comment by kpsherva** [comment]
requires adding more fields to the user (check https://github.com/inveniosoftware/invenio-userprofiles and https://github.com/inveniosoftware/invenio-accounts-rest)

( require https://github.com/inveniosoftware/invenio-app-ils/issues/103 )

**Comment by zzacharo** [comment]
We should add to `invenio-userprofiles` in the additional data the `locationPid` and use that one in `jwt.py`
