### ISSUE TITLE
checkout does not work

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#710]
reproduce:
1.  go to a loan which is pending 
2. try to checkout one of the available items
3. you get
```
invenio_records_rest.loaders.marshmallow.MarshmallowErrors: 400 Bad Request: Validation error.. Encountered errors: [{'parents': (), 'field': 'transaction_user_pid', 'message': 'Not a valid string.'}]

```

**Comment by ntarocco** [comment]
You might have tested this after merging and releasing `invenio-circulation` and not merging my PR. It should work in my PR.

**Comment by kpsherva** [comment]
checked, works.
