### ISSUE TITLE
Document: convert publication_year to number

### ISSUE THREAD

**Issue by topless** [inveniosoftware/invenio-app-ils#718]
In the document model, the following fields are now treated as string and they might be treated as dates instead:
* `publication_year`
* `imprint.date`
* `imprint.reprint_date`

If decided to change them to dates, then the following places should be also changed:
* Python JSON loaders
* JS document serializer
* search/details pages when displayed
* form editor input

**Comment by kpsherva** [comment]
decided to leave as string
