### ISSUE TITLE
global: $ref resolvers extras

### ISSUE THREAD

**Issue by topless** [inveniosoftware/invenio-app-ils#72]
During the implementation of resolvers several issues popped up. 

- [ ] Deprecate `JSONSCHEMAS_HOST`, it is a dummy domain and it is used from the resolvers to avoid url conflicts with rest api. `$ref` properties don't work with relative urls and currently we don't have access to `request` to get our current host.
- [ ] There is an ongoing [invenio-records-rest issue](https://github.com/inveniosoftware/invenio-records-rest/issues/232) with the `PID` being part of the `schema` for create and update.
- [ ] Since CDS will wrap ILS our resolvers have to be overridable.

**Comment by kpsherva** [comment]
closing as stale
