### ISSUE TITLE
Display domain-specific identifiers

### ISSUE THREAD

**Issue by equadon** [inveniosoftware/invenio-app-ils#721]
Currently, identifiers are stored as an array of objects with a `scheme` and `value`. The `scheme` is a vocabulary and for e.g. series `ISSN` and `ISBN` are identifiers we want to display separately but they are grouped together with the other identifiers.

* Should we have a unified way of handling identifiers in ILS?
* How should we store these identifiers?
* How do we display them?
* Should `scheme` be a vocabulary?

**Comment by ntarocco** [comment]
This can be closed I believe. WDYT? @kprzerwa

**Comment by kpsherva** [comment]
discussed, closing
