### ISSUE TITLE
acquisition: order property created_by_pid

### ISSUE THREAD

**Issue by topless** [inveniosoftware/invenio-app-ils#739]
In the acquisition order we introduced a property `created_by_id`. In the payload we are also providing `cretad_by` which holds the same value. The pid on its own is not enough to describe different type of creators i.e. patrons and other systems. Maybe we should align and do it in the same fashion its done for the document:

```python
"created_by": {
  "properties": {
    "type": {
      "type": "string"
    },
    "value": {
      "type": "string"
    }
  },
  "type": "object"
},
```

**Comment by kpsherva** [comment]
closing as done in https://github.com/inveniosoftware/invenio-app-ils/blob/6da7d715477dc9a8c862a62048663ecce12d64c9/invenio_app_ils/acquisition/schemas/acq_orders/order-v1.0.0.json#L136
