### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by janequist** [inveniosoftware/invenio-app-ils#749]
Hi,

Getting errors when trying to install using the scripts provided. It seems there is a conflict.

1. First, get this error:
ERROR: invenio-stats 1.0.0a15 has requirement kombu<4.4,>=4.2.0, but you'll have kombu 4.6.7 which is incompatible.
ERROR: invenio-celery 1.1.1 has requirement celery<4.3.0,>=4.2.1, but you'll have celery 4.4.0 which is incompatible.

2. Then upon uninstalling 4.4 and installing 4.2.1, get this error:
ERROR: flask-celeryext 0.3.3 has requirement celery>=4.3; python_version == "3.7", but you'll have celery 4.2.1 which is incompatible.

Plz address.
Thanks,
mj

**Comment by kpsherva** [comment]
Hello there!
We are currently working on solving that problem.  I will let you know here once it is solved.

Also from your description I understand that you are using python 3.7 - which is not currently fully supported yet, and you might experience some issues with this configuration.

Please keep in mind that this application is still under ongoing development, and it is not stable, as we keep merging to master and there might be issues. We will take a look into having possible stable versions in the future.

**Comment by kpsherva** [comment]
@janequist the issue was solved in the linked PR

**Comment by janequist** [comment]
Thanks
