### ISSUE TITLE
config: permission review

### ISSUE THREAD

**Issue by topless** [inveniosoftware/invenio-app-ils#755]
Review and adjust all permissions for  all `RECORDS_REST_ENDPOINTS`.

- `create_permission_factory_imp`
- `delete_permission_factory_imp`
- `list_permission_factory_imp`
- `read_permission_factory_imp`
- `update_permission_factory_imp`

**Comment by kpsherva** [comment]
please write also documentation about which role should have access by endpoint and to UI components

**Comment by ntarocco** [comment]
@topless was there any issue here? What was the problem?

**Comment by topless** [comment]
@ntarocco, some of them were allow_all when they shouldn't, and the `list_permission` was missing which you fixed.
