### ISSUE TITLE
global: refactor and naming consistency

### ISSUE THREAD

**Issue by topless** [inveniosoftware/invenio-app-ils#757]
- [ ] reject -> cancel (document requests, loans and wherever is applicable)
- [ ] `state` and `status`, we should align and use the same term for all
- [ ] `login` & `sign in`, both terms are use, we should pick one and stick to it
- [ ] prefix underscores for all `lodash` imports and usage

**Comment by kpsherva** [comment]
Cancel in the context of loan and the document request makes sense from the perspective of user. User makes a request (loan or for the document) and then cancels it, for whatever reason (changes the decision, and terminates the workflow)
Reject has a meaning as an action of the librarian, so the decision is the part of the workflow.

`State` - virtual
`Status` -  physical

`Sign in` is a trend now for the UI, but on the backend I don't mind to call it login

**Comment by topless** [comment]
It still feels confusing to me, so I looked up the definitions of each:

`state`: the particular condition that **someone** or **something** is in at a specific time 
(in both cases refers to something that exists, non virtual)

`status`: the situation at a particular time during a process /
status can also mean state or condition at a particular time
(it feels like that this one should refer to virtual stuff)

`Sign in`
- When I click a button called sign in and my url writes login (but I don't really care how we name it in the back end)
- There is the header button that has the label Sign in, and then for example in the literature page if the user is not signed in, the button says login to do stuff ... we should keep the same term for the frontend
- And we should of course keep the opposite function in the same terminology, Sign Up/Sign In/Sign Out or Sign Up/ Login/Logout

Whichever term we use, users are aware of what we are trying to communicate so the point is to just keep the same everywhere.
