### ISSUE TITLE
fix setup script path to vocabularies

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#823]
https://github.com/inveniosoftware/invenio-app-ils/blob/2216de96bd77fc5b5c2a0f5eb05adada424481b3/invenio_app_ils/cli.py#L1028
this line causes ILS demo data failing in CLI of an overlay when ILS installed as a dependency. 
change to path that gets the demo vocabularies from virtualenv installation of ILS 
now it get's it from the root of ILS itself

**Comment by ntarocco** [comment]
See InvenioRDM solution:
```
{
    'resource_types': join(
        dirname(abspath(__file__)),
        'app_data', 'vocabularies', 'resource_types.csv')
}
```
doc: https://inveniordm.docs.cern.ch/develop/make_it_your_own/#define-a-custom-controlled-vocabulary
