### ISSUE TITLE
Documentation on config file

### ISSUE THREAD

**Issue by kvslee** [inveniosoftware/invenio-app-ils#899]
Hi, I am confused in setting up a config file. Based on this resource, https://invenioils.docs.cern.ch/quickstart/, I have to create a file, invenio.cfg, in ~/.virtualenvs/invappils/var/instance. But following this resource, https://invenio-app-ils.readthedocs.io/en/latest/installation.html, we use the file, config.py and add a token in ./invenio_app_ils/ui/.env.development. Which one is right?

**Comment by ntarocco** [comment]
Hi, please ignore the ReadTheDocs website, I will actually remove it if it is indeed creating confusion.
The official documentation is https://invenioils.docs.cern.ch/quickstart/.

Note that when the [current ongoing PR](https://github.com/inveniosoftware/invenio-app-ils/pull/903) will be merged (normally by tomorrow), you won't need the extra step of having to set the `ILS_DEFAULT_LOCATION_PID` variable, we are removing it.

**Comment by ntarocco** [comment]
I have update the main readme and hopefully removed this confusion. Thanks for reporting it!
