### ISSUE TITLE
change license schema field

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#916]
```
'license': {
  'licence': ...opendefinition fields,
  'material': ...
}
```
Funder and internal note fields to be confirmed on the meeting on the 28th Jul

**Comment by topless** [comment]
I will need some clarifications for the issue, possibly mrs @kprzerwa can shed some light!

- The schema field is `licenses` and belongs to document
- Then what do we expect, do we have a license inside the license?
```
'license': {
  'licence': {...opendefinition fields},
  'material': ...
}
```
- The opendefinition fields that we store in our vocaburaries are `url`, `maintainer`,  `status`
- What type is `material`?
- `Funder` and `internal note` fields to be confirmed, did they get confirmed? If so what type of fields are they?

**Comment by kpsherva** [comment]
the structure will be as follows (pseudocode)
```
'licenses': {
       "items": {
        "properties": {
               "licence": { 
                  list of fields linked below
               },
               "material": .....
               "internal_note": .....
         }
      },
      "minItems": 1,
      "title": "List of licenses of the document (Vocabulary)",
      "type": "array",
      "uniqueItems": true
}
```
list of possible license fields:
https://github.com/inveniosoftware/invenio-opendefinition/blob/master/invenio_opendefinition/jsonschemas/licenses/license-v1.0.0.json

we use currently: ``` id, status, maintainer, url, title ```, it stays like this in this case

`material` is the same type as in the other record types (string - to be checked)
`funder` is dropped

the license is inside of licenses, because on top of the standard opendefinition licence fields we have additional ones from the library.
