### ISSUE TITLE
ILL: borrowing request remains in the "requests" as pending after being processed

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-ils#973]
### How to reproduce

Create loan from `Borrowing request`, it works and the loan appears in the Patron view but the entry remains in `Your requests` for new literature as `Pending`.

I can also cancel it, and it cancels the request for new literature, while on Loan already.

### How it should work

The borrowing request should have changed state, and be visible in the patrons history

Document the workflow of this feature

**Comment by FlorianCassayre** [comment]
~It's unclear to me how borrowing requests are related to literature requests. Maybe I'm missing something~

~**Edit**: got it, my bad. I had forgotten about this feature. However I cannot reproduce it, when I create a loan from a borrowing request, the loan does correctly appear under `Ongoing loans` in the patron details. When canceled, the loan is moved to `Loans history`.~

* as a patron, create a literature request
* as a librarian, from the literature request details page, create a (or select an existing) document
* as a librarian, create a borrowing request, link it to the request and click on "Review"
* as patron, the request has disappeared from "Your requests for new literature"

~The only thing that I notice is that the patron can't see it anymore once it has been finalized.~

=> It appears in the history

**Comment by kpsherva** [comment]
the workflow was explained, the literature request appears in the patron's `history`
